// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABLZpPVFhE-Fo7Khdq-WDhmchUiyotTCE',
    appId: '1:797562607983:web:ed529bd70b758bfe63f09a',
    messagingSenderId: '797562607983',
    projectId: 'iot-transportation-monitoring',
    authDomain: 'iot-transportation-monitoring.firebaseapp.com',
    storageBucket: 'iot-transportation-monitoring.firebasestorage.app',
    measurementId: 'G-Q805EBXB8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23Mqp9t5H07tu9ajWgpfjRL3xpb8OCMQ',
    appId: '1:797562607983:android:a04ddf11b97a8eac63f09a',
    messagingSenderId: '797562607983',
    projectId: 'iot-transportation-monitoring',
    storageBucket: 'iot-transportation-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTC1XPTkccrt3tnbYrVifQR-Z9YcTbO8',
    appId: '1:797562607983:ios:a79b492dd963595263f09a',
    messagingSenderId: '797562607983',
    projectId: 'iot-transportation-monitoring',
    storageBucket: 'iot-transportation-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.transportingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTC1XPTkccrt3tnbYrVifQR-Z9YcTbO8',
    appId: '1:797562607983:ios:a79b492dd963595263f09a',
    messagingSenderId: '797562607983',
    projectId: 'iot-transportation-monitoring',
    storageBucket: 'iot-transportation-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.transportingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABLZpPVFhE-Fo7Khdq-WDhmchUiyotTCE',
    appId: '1:797562607983:web:0a9706565d89746363f09a',
    messagingSenderId: '797562607983',
    projectId: 'iot-transportation-monitoring',
    authDomain: 'iot-transportation-monitoring.firebaseapp.com',
    storageBucket: 'iot-transportation-monitoring.firebasestorage.app',
    measurementId: 'G-EMB5H26R4R',
  );
}
